cache:
  key: "$CI_COMMIT_REF_NAME-$CI_JOB_STAGE"
  paths:
    - .composer/

before_script:
  - apk add git --update

stages:
  - php
  - typoscript
  - yaml
  #- fluid
  #- xliff

.php: &phptesting
  stage: php
  image: php:$DOCKER_TAG
  only:
    - branches
  before_script:
    - export TYPO3_PATH_WEB="$PWD/.Build/Web"
    - export COMPOSER_CACHE_DIR=.composer
    - curl -OLs https://composer.github.io/installer.sig
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php -r "if (hash_file('SHA384', 'composer-setup.php') === trim(file_get_contents('installer.sig'))) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    - php composer-setup.php --no-ansi --install-dir=/usr/bin --filename=composer
    - php -r "unlink('composer-setup.php'); unlink('installer.sig');"
    - composer require friendsofphp/php-cs-fixer
  script:
    - .Build/bin/php-cs-fixer fix --dry-run --config=.php_cs --diff

# Tests in PHP 7.2 and TYPO3 9.5 version
php:testphp72:typo3_95:
  <<: *phptesting
  variables:
    DOCKER_TAG: 7.2-alpine
    # TYPO3_VERSION: ^9.5

typoscript:test:
  image: composer:1.6
  stage: typoscript
  before_script:
    - export COMPOSER_CACHE_DIR=.composer
    - composer require --dev helmich/typo3-typoscript-lint
  script:
    - .Build/bin/typoscript-lint -c tslint.yaml

yaml:test:
  image: python:alpine3.7
  stage: yaml
  before_script:
    - pip install yamllint==1.10.0
  script:
    - yamllint -c .yamllint .

#fluid:test:
#  image: composer:1.6
#  stage: fluid
#  before_script:
#    - export COMPOSER_CACHE_DIR=.composer
#    - composer require typo3fluid/fluid-lint:dev-master
#  script:
#    - .Build/bin/fluidlint Resources/Private/Templates/Default.html

#xliff:test:
#  image: composer:1.6
#  stage: xliff
#  before_script:
#    - export COMPOSER_CACHE_DIR=.composer
#    #- apk --no-cache add libxml2-utils
#    #- wget https://raw.githubusercontent.com/symfony/translation/v4.1.1/Resources/schemas/xliff-core-1.0-strict.xsd
#    - composer require symfony/translation
#  script:
#    - .Build/bin/xlifflint /usr/local/bin/php lint:xliff /Resources/Private/Language
#    #- xmllint --schema xliff-core-1.0-strict.xsd --noout $(find Resources -name '*.xlf')
