language: php

php:
  - 7.2

#env:
#  - TYPO3_VERSON="9.5"

sudo: false

notifications:
  email: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  #- composer require typo3/minimal ${TYPO3_VERSON} --update-with-dependencies
  #- composer require nimut/testing-framework
  - composer require friendsofphp/php-cs-fixer
  - composer require --dev helmich/typo3-typoscript-lint
  - pip install yamllint==1.10.0

script:
  - .Build/bin/php-cs-fixer fix --dry-run --config=.php_cs --diff
  - .Build/bin/typoscript-lint -c tslint.yaml
  - yamllint -c .yamllint .
